const UserActionTypes = {
	CHECK_USER_SESSION: 'CHECK_USER_SESSION',
	GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
}

export default UserActionTypes;